### ISSUE TITLE
Figure out how to use keyboard.send_keys() in 'wrap_clip' function

### ISSUE THREAD

**Issue by ernstki** [ernstki/autokey-config#3]
The thing about that is 

```python
>>> from autokey import scripting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/.local/lib/python3.5/site-packages/autokey/scripting.py", line 19, in <module>
    from . import common, model, iomediator
  File "/home/USER/.local/lib/python3.5/site-packages/autokey/model.py", line 19, in <module>
    from .configmanager import *
  File "/home/USER/.local/lib/python3.5/site-packages/autokey/configmanager.py", line 722, in <module>
    class GlobalHotkey(AbstractHotkey):
NameError: name 'AbstractHotkey' is not defined
name 'AbstractHotkey' is not defined
```

...so I don't know how to do `keyboard.send_keys()` in a script that's "included" by AutoKey  like `lib/scriptlib.py` is.

I could make it a "real" AutoKey script, so that there's already a `keyboard` object in scope, but the `engine.run_script` method used [here](https://github.com/autokey/autokey/wiki/Scripting#key-wrapper) doesn't seem to work.

**Comment by ernstki** [comment]
I think making it a "real" AutoKey script and using `engine.run_script` will work fine if the clipboard is the means of passing "arguments."
